Feature/0.0.2
lunasoft/sw-java-toolkit pull request #4
Opened 2018-07-04 17:37 UTC by ecs515

2018-07-04 21:30 UTC, rbarusta approved these changes

2018-07-04 21:47 UTC, BalderramaJFP approved these changes

2018-07-04 22:48 UTC, hermesw requested changes
Es necesario cambiar las funciones que utilizan File como parámetro para leer archivos y que en vez de eso reciban un arreglo de bytes.

2018-07-04 22:48 UTC, hermesw commented on README.md
> +X509Certificate x509Cer = Sign.certificateGetX509(new File("C:\\CSD_Pruebas_CFDI_LAN7008173R5.cer"));
No deberiamos utilizar funciones que hagan referencia a archivos. Existe otra forma de leer el certificado? a partir de bytes[]?

2018-07-04 22:48 UTC, hermesw commented on README.md
> +String keyB64 = Sign.keyBase64get("C:\\CSD_Pruebas_CFDI_LAN7008173R5.key");
No deberiamos de utilizar funciones que hagan referencia a archivos para cargar la llave, deberia recibir bytes[].

2018-07-04 22:48 UTC, hermesw commented on README.md
> +comprobante.save(xmlFile, xmlOptions);
La funcion para obtener el xml deberia regresarlo en un string y no tenerlo que guardar a un archivo.

2018-07-05 18:01 UTC, ecs515 commented on README.md
> +X509Certificate x509Cer = Sign.certificateGetX509(new File("C:\\CSD_Pruebas_CFDI_LAN7008173R5.cer"));
ya se hicieron los cambios

2018-07-05 18:02 UTC, ecs515 commented on README.md
> +String keyB64 = Sign.keyBase64get("C:\\CSD_Pruebas_CFDI_LAN7008173R5.key");
ya se hicieron los cambios

2018-07-05 18:47 UTC, hermesw requested changes
Todo se ve bien, solo cambiar la forma de generar la cadena original el como obtener el xslt.

2018-07-05 18:47 UTC, hermesw commented on src/main/java/Sign/Sign.java
>              Source xslt = new StreamSource(new File(filePath.concat("/src/main/Resources/assets/cadenaoriginal_3_3.xslt")));
Hay que cambiar el uso de Archivo fisico para el xslt  por embedded resource. De esta manera no dependemos de que el archivo exista fisicamente en el path , el JAR lo incluye sin tener que hacer referencia a paths externos. 

https://stackoverflow.com/questions/3721706/embedding-resources-images-sound-bits-etc-into-a-java-project-then-use-those
https://capturevision.wordpress.com/2008/06/28/how-to-embed-resource-files-using-netbeans/

2018-07-05 21:17 UTC, alxcodes approved these changes

2018-07-05 21:53 UTC, ecs515 commented on src/main/java/Sign/Sign.java
>              Source xslt = new StreamSource(new File(filePath.concat("/src/main/Resources/assets/cadenaoriginal_3_3.xslt")));
Según el intellij ya quedo xD

2018-07-05 21:53 UTC, merged